export const RESPONSE_MESSAGE = {
  BASE_ROUTE: "This is the base route",
  NOT_FOUND: "The requested resource was not found",
  INTERNAL_SERVER_ERROR: "Internal server error",
  EMAIL_EXISTS: "Email already exists",
  EMAIL_NOT_EXISTS: "Email do not exits",
  PASSWORD_NOT_MATCH: "Password and confirm password should be same",
  REGISTRATION_SUCCESSFUL:
    "Registration successful.Please check your email for further instructions",
  SOMETHING_WENT_WRONG: "Something went wrong.Please try again later",
  WRONG_CREDENTIAL: "Wrong credential",
  SIGN_IN_SUCCESSFUL: "Sign In successful",
  EMAIL_VERIFIED: "Email verified successfully.Please login",
  ACCESS_TOKEN_GENERATED: "Access token generated successfully",
  LOGIN_AGAIN: "Please login again.",
  UNAUTHORIZED_ACCESS: "Unauthorized access.",
  NO_DATA: "No data found",
  SUCCESSFULLY_GET_ALL_DATA: "Successfully get the data",
  VERIFY_EMAIL: "Please verify your email before login",
  BALANCE_UPDATED: "Balance updated successfully",
  UNPROCESSABLE_ENTITY: "Unprocessable entity",
  UPLOAD_FAILED: "Failed to upload file",
  DP_UPDATED: "Profile picture updated successfully",
  USER_DISABLED: "User disabled successfully",
  USER_RESTRICTED: "You cannot login .Your account is restricted.",
  UPDATE_FAILED: "Failed to update the data",
  UPDATE_SUCCESS: "Successfully Updated",
  REQUEST_RESET_PASSWORD:
    "Successfully request for reset password.Please check your email",
  COURSE_CREATED: "Course created successfully",
  COURSE_TITLE: "Course with this title already exists",
  S3_SERVER_ERROR: "Server error cannot get the data right now",
  S3_SERVER_SUCCESS: "File uploaded successfully",
  COURSE_SECTION_CREATED: "Course section created successfully",
  DELETE_SUCCESS: "Deleted data successfully",
  DELETE_FAILED: "Can not delete right now.Try again later",
  COURSE_ALREADY_IN_CART: "The course is already exists in the cart",
  COURSE_ADDED_TO_CART: "Course added to cart successfully",
  NO_CART: "Cart cart found for the user",
  CART_UPDATED: "Course successfully removed from cart",
  COURSE_ALREADY_IN_WISHLIST: "The course is already exists in the wishlist",
  COURSE_ADDED_TO_WISHLIST: "Course added to wishlist successfully",
  NO_WISHLIST: "Wishlist wishlist found for the user",
  WISHLIST_UPDATED: "Course successfully removed from wishlist",
  COURSE_NOT_FOUND: "No course found associated with this id",
  COURSE_SECTION_NOT_FOUND: "No course section found associated with this id",
  ASSIGNMENT_CREATE_FAILED: "Cannot create assignment now.Try again later",
  ASSIGNMENT_CREATE_SUCCESS: "Assignment created successfully",
  ASSIGNMENT_UPDATE_FAILED: "Cannot update assignment now.Try again later",
  ASSIGNMENT_UPDATE_SUCCESS: "Assignment updated successfully",
  ASSIGNMENT_NOT_FOUND: "No assignment found associated with this id",
  ASSIGNMENT_DISABLE_SUCCESS: "Assignment disabled successfully",
  ASSIGNMENT_DISABLE_FAILED: "Assignment disabled failed",
  ASSIGNMENT_ENABLE_SUCCESS: "Assignment enabled successfully",
  ASSIGNMENT_ENABLE_FAILED: "Assignment enabled failed",
  SINGLE_ASSIGNMENT: "Can not add more than one assignment",
  SUBSCRIPTION_FAILED:
    "Can not apply for subscription now.Please try again later",
  SUBSCRIPTION_SUCCESS:
    "Successfully applied for subscription.Please wait for the approval",
  SUBSCRIPTION_ACCEPTED_SUCCESS: "Subscription Accepted",
  SUBSCRIPTION_REJECTED_EMAIL: "Subscription rejected email sent",
  ASSIGNMENT_SUBMIT_FAILED: "Failed to submit assignment",
  ASSIGNMENT_SUBMIT_SUCCESS: "Successfully submitted the assignment",
  CATEGORY_EXISTS: "Category already exist",
  CATEGORY_CREATE_SUCCESS: "Successfully created new category",
  CATEGORY_CREATE_FAILED: "Can not add category now",
  INVALID_GRADE: "Invalid grade provided",
  ASSIGNMENT_ASSESSMENT_SUCCESS: "Successfully submitted the assessment",
  ASSIGNMENT_ASSESSMENT_FAIlED: "Assignment assessment failed",
  SUBSCRIBE_COURSE_BEFORE_ADDING_REVIEW:
    "Subscribe the course before adding review or rating",
  ADD_REVIEW_FAILED: "Failed to add review",
  ADD_REVIEW_SUCCESS: "Successfully added a review",
  REVIEW_EXISTS: "You can not add more than 1 review",
  UPDATE_REVIEW_FAILED: "Failed to UPDATE review",
  UPDATE_REVIEW_SUCCESS: "Successfully updated the review",
  DELETE_REVIEW_FAILED: "Failed to delete review and rating",
  DELETE_REVIEW_SUCCESS: "Successfully deleted review and rating",
  QUIZ_CREATE_SUCCESS: "Quiz Created successfully",
  QUIZ_CREATE_FAILED: "Can not create quiz now",
  QUIZ_UPDATE_FAILED: "Can not update quiz now",
  QUIZ_UPDATE_SUCCESS: "Quiz updated successfully",
  QUESTION_DELETE_FAILED: "Can not delete question now",
  QUESTION_DELETE_SUCCESS: "Question deleted successfully",
  QNA_ADDED_SUCCESS: "Question posted successfully",
  QNA_ADDED_FAILED: "Question posting failed",
  REPLY_SUCCESS:"Replied successfully",
  REPLY_FAIL:"Reply failed",
  QNA_UPDATE_SUCCESS:"Question updated successfully",
  QNA_UPDATE_FAILED:"Question failed to update",
  REPLY_DELETE_SUCCESS:"Reply deleted successfully",

};
